# coding: utf-8

from setuptools import setup, find_packages

NAME = "unicorn_server"
VERSION = "0.1.1"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["connexion"]

setup(
    name=NAME,
    version=VERSION,
    description="Example Unicorn Server (An ALTO Extension)",
    author_email="snlab.org@gmail.com",
    url="",
    keywords=["Swagger", "Example Unicorn Server (An ALTO Extension)"],
    install_requires=REQUIRES,
    packages=find_packages(),
    package_data={'': ['swagger/swagger.yaml']},
    include_package_data=True,
    long_description="""\
    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
    """
)

