swagger: "2.0"
info:
  version: "0.1.0"
  title: Basic Data Type of ALTO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  Vtag:
    properties:
      resource-id:
        type: string
      tag:
        type: string
    required:
    - resource-id
    - tag
    type: object
  DependentVtags:
    items:
      $ref: "#/definitions/Vtag"
    type: array
  Pid:
    pattern: ^[0-9a-zA-Z-:@_\.]{1,64}$
    type: string
  Pids:
    items:
      $ref: "#/definitions/Pid"
    type: array
  CostType:
    properties:
      cost-metric:
        id: /alto/types/cost-type/properties/cost-metric
        type: string
      cost-mode:
        id: /alto/types/cost-type/properties/cost-mode
        type: string
    required:
    - cost-mode
    - cost-metric
    type: object
  Constraints:
    items:
      type: string
    type: array
  Ipv4Addr:
    type: string
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
  TypedEndpointAddr:
    pattern: ^(ipv6:(((?=.*(::))(?!.*\4.+\4))\4?|([\da-fA-F]{1,4}(\4|:\b|$)|\2))(?5){5}((?5){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})|ipv4:(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
    type: string
  Endpoints:
    items:
      $ref: "#/definitions/TypedEndpointAddr"
    type: array
