swagger: "2.0"
info:
  version: "0.1.0"
  title: Basic Data Type of ALTO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  ResourceID:
    pattern: ^[0-9a-zA-Z-:@_\.]{1,64}$
    type: string
  CostMetric:
    pattern: ^[0-9a-zA-Z-:@_\.]{1,64}$
    type: string
  CostMode:
    type: string
  Vtag:
    properties:
      resource-id:
        $ref: "#/definition/ResourceID"
      tag:
        type: string
    required:
    - resource-id
    - tag
    type: object
  DependentVtags:
    items:
      $ref: "#/definitions/Vtag"
    type: array
  Pid:
    pattern: ^[0-9a-zA-Z-:@_\.]{1,64}$
    type: string
  Pids:
    items:
      $ref: "#/definitions/Pid"
    type: array
  CostType:
    properties:
      cost-metric:
        id: /alto/types/cost-type/properties/cost-metric
        $ref: "#/definition/CostMetric"
      cost-mode:
        id: /alto/types/cost-type/properties/cost-mode
        $ref: "#/definition/CostMode"
    required:
    - cost-mode
    - cost-metric
    type: object
  Constraints:
    items:
      type: string
    type: array
  Ipv4Addr:
    type: string
    pattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$
  TypedEndpointAddr:
    pattern: ^(ipv4:(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))|(ipv6:((:|[0-9a-fA-F]{0,4}):)([0-9a-fA-F]{0,4}:){0,5}((([0-9a-fA-F]{0,4}:)?(:|[0-9a-fA-F]{0,4}))|(((25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9]?[0-9])))(%[a-zA-Z0-9]+)?)|(ipv6:(([^:]+:){6}(([^:]+:[^:]+)|(.*\..*)))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?)(%.+)?;)$
    type: string
  Endpoints:
    items:
      $ref: "#/definitions/TypedEndpointAddr"
    type: array
