swagger: "2.0"
info:
  version: "0.1.0"
  title: EndpointProperty Type of ALTO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  Request:
    properties:
      endpoints:
        $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Endpoints"
      properties:
        id: /properties/properties
        items:
          id: /properties/properties/items
          pattern: ^[0-9a-zA-Z-:@_\.]{1,64}$
          type: string
        type: array
    required:
    - endpoints
    - properties
    type: object
  Response:
    properties:
      endpoint-properties:
        id: /properties/endpoint-properties
        patternProperties:
          ^(ipv6:(((?=.*(::))(?!.*\4.+\4))\4?|([\da-fA-F]{1,4}(\4|:\b|$)|\2))(?5){5}((?5){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})|ipv4:(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$:
            id: /properties/endpoint-properties/patternProperties/endpoint
            patternProperties:
              ^[0-9a-zA-Z-:@_\.]{1,64}$:
                id: /properties/endpoint-properties/patternProperties/endpoint/patternProperties/property
                type: string
            type: object
        type: object
      meta:
        id: /properties/meta
        properties:
          dependent-vtags:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/DependentVtags"
        required:
        - dependent-vtags
        type: object
    required:
    - endpoint-properties
    - meta
    type: object
