swagger: "2.0"
info:
  version: "0.1.0"
  title: EndpointCost Type of ALTO
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: SNLab.Org
    url: https://snlab.github.io/
    email: snlab.org@gmail.com
paths: {}
definitions:
  Request:
    properties:
      constraints:
        $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Constraints"
      cost-type:
        $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/CostType"
      endpoints:
        id: /properties/endpoints
        properties:
          dsts:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Endpoints"
          srcs:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/Endpoints"
        required:
        - srcs
        - dsts
        type: object
    required:
    - cost-type
    - endpoints
    type: object
  Response:
    properties:
      endpoint-cost-map:
        id: /properties/endpoint-cost-map
        patternProperties:
          ^(ipv6:(((?=.*(::))(?!.*\4.+\4))\4?|([\da-fA-F]{1,4}(\4|:\b|$)|\2))(?5){5}((?5){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})|ipv4:(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$:
            id: /properties/endpoint-cost-map/partternProperties/src
            patternProperties:
              ^(ipv6:(((?=.*(::))(?!.*\4.+\4))\4?|([\da-fA-F]{1,4}(\4|:\b|$)|\2))(?5){5}((?5){2}|(((2[0-4]|1\d|[1-9])?\d|25[0-5])\.?\b){4})|ipv4:(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))$:
                id: /properties/endpoint-cost-map/patternProperties/src/patternProperties/dst
            type: object
        type: object
      meta:
        id: /properties/meta
        properties:
          cost-type:
            $ref: "https://github.com/openalto/alto-swagger/raw/spec/api/basic.yaml#/definitions/CostType"
        required:
        - cost-type
        type: object
    required:
    - meta
    - endpoint-cost-map
    type: object
